spring:
  application.name: Blockchain-Identity-Logic
  profiles.active: default

blockchain.identity:
  protocol: http

---
spring:
    profiles: default
blockchain.identity:
  core:
    port: 8080
    address: localhost
  discoveryService:
    port: 8080
    address: localhost
---
spring:
    profiles: production
blockchain.identity:
  core:
    port: 8080
    address: srv01.snet.tu-berlin.de
  discoveryService:
    port: 8080
    address: srv01.snet.tu-berlin.de
