spring:
  application.name: Blockchain-Identity-Logic
  profiles.active: default
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: beer-sample
      password:

blockchain.identity:
  protocol: http


---
spring:
    profiles: default
blockchain.identity:
  core:
    port: 8080
    address: localhost
  discoveryService:
    port: 8101
    address: localhost
  database:
    port: 8091
    address: srv01.snet.tu-berlin.de
---
spring:
    profiles: production
blockchain.identity:
  core:
    port: 8100
    address: srv01.snet.tu-berlin.de
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  database:
    port: 8091
    address: srv01.snet.tu-berlin.de