spring:
  application.name: Blockchain-Identity-User
  profiles.active: default
  couchbase:
    env:
      timeouts:
        connect: 10000
        query: 75000
        view: 75000
        socket-connect: 10000

blockchain.identity:
  protocol: http
  type: USER

---
spring:
  profiles: default
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: default
      password: password
blockchain.identity:
  core:
    port: 8080
    address: ${user.name}
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  ethereum:
    port: 7111
    address: srv01.snet.tu-berlin.de
---
spring:
  profiles: test
  couchbase:
    bootstrap-hosts: srv01.snet.tu-berlin.de
    bucket:
      name: claim_test
      password: 1234qwer
blockchain.identity:
  core:
    port: 8080
    address: localhost
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  ethereum:
    port: 7111 # set by jenkins
    address: srv01.snet.tu-berlin.de
---
spring:
  profiles: production
  couchbase:
    bootstrap-hosts: srv01.snet.tu-berlin.de
    bucket:
      name: user
      password: 1234qwer
blockchain.identity:
  core:
    port: 1112
    address: srv01.snet.tu-berlin.de
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  ethereum:
    port: 7111
    address: srv01.snet.tu-berlin.de