spring:
  application.name: Blockchain-Identity-Logic
  profiles.active: default

blockchain.identity:
  protocol: http
  provider.credentials:
    username: admin
    password: penispumpe

---
spring:
    profiles: default
blockchain.identity:
  core:
    port: 8080
    address: localhost
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  ethereum:
    port: 8545
    address: localhost
---
spring:
    profiles: production
blockchain.identity:
  core:
    port: 8100
    address: srv01.snet.tu-berlin.de
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  ethereum:
    port: 8545
    address: srv01.snet.tu-berlin.de
