spring:
  application.name: Blockchain-Identity-Provider
  profiles.active: default

blockchain.identity:
  protocol: http
  provider.credentials:
    username: admin
    password: penispumpe

---
spring:
  profiles: default
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: default
      password: password
blockchain.identity:
  type: PROVIDER
  core:
    port: 8080
    address: localhost
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  ethereum:
    port: 8545
    address: localhost
---
spring:
  profiles: test
  couchbase:
    bootstrap-hosts: srv01.snet.tu-berlin.de
    bucket:
      name: claim_test
      password: 1234qwer
blockchain.identity:
  type: PROVIDER
  core:
    port: 8080
    address: localhost
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  ethereum:
    port: 8545
    address: localhost
---
spring:
  profiles: production
  couchbase:
    bootstrap-hosts: srv01.snet.tu-berlin.de
    bucket:
      name: provider
      password: 1234qwer
blockchain.identity:
  type: GOVERMENT
  core:
    port: 8100
    address: srv01.snet.tu-berlin.de
  discoveryService:
    port: 8101
    address: srv01.snet.tu-berlin.de
  ethereum:
    port: 8545
    address: srv01.snet.tu-berlin.de
