spring:
  application.name: Blockchain-Identity-Logic
  profiles.active: default
---
spring:
  profiles: default
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: default
      password: password
---
spring:
  profiles: test
  couchbase:
    bootstrap-hosts: srv01.snet.tu-berlin.de
    bucket:
      name: discovery_test
      password: 1234qwer